apiVersion: v1
kind: Service
metadata:
  name: #{appName}#
spec:
  selector:
    app: #{appName}#
  ports:
    - protocol: TCP
      port: #{svcPort}#
      targetPort: #{cntrPort}#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{appName}#
  labels:
    app: #{appName}#
spec:
  replicas: #{replicasNumber}#
  revisionHistoryLimit: #{historyNumber}#
  selector:
    matchLabels:
      app: #{appName}#
  template:
    metadata:
      labels:
        app: #{appName}#
    spec:
      containers:
        - name: #{appName}#
          image: #{acrLoginServer}#/#{imageName}#:#{Build.BuildId}#
          ports:
            - containerPort: #{cntrPort}#
          volumeMounts:
            - name: #{appName}#
              mountPath: #{vlmMounthPath}#
              readOnly: true
            - name: ai-#{appName}#
              mountPath: /tmp/app-insights
      volumes:
        - name: #{appName}#
          secret:
            secretName: #{appName}#
        - name: ai-#{appName}#
          emptyDir: {}
